export const troubleBrewing = [
  { "id": "_meta",
    "name": "Trouble Brewing",
    "author": "The Pandemonium Institute",
    "almanac": "https://wiki.bloodontheclocktower.com/Trouble_Brewing"
  },
  "chef",
  "empath",
  "fortune_teller",
  "investigator",
  "librarian",
  "mayor",
  "monk",
  "ravenkeeper",
  "slayer",
  "soldier",
  "undertaker",
  "virgin",
  "washerwoman",
  "butler",
  "drunk",
  "recluse",
  "saint",
  "baron",
  "poisoner",
  "scarlet_woman",
  "spy",
  "imp",
  "bureaucrat",
  "gunslinger",
  "scapegoat",
  "beggar",
  "thief"
]